name: Starstone3
version: '${project.version}'
main: org.battlecraft.starstone3.Starstone3
api-version: '1.20'
commands:
  summonstarstone:
    description: Summon a Starstone block
    usage: /summonstarstone
    permission: starstone.summon
permissions:
  starstone.summon:
    description: Allows the player to summon a Starstone block
    default: op
